version: "3"
services:
  domain:
    build:
      context: .
      dockerfile: router.Dockerfile
    # ports:
    #   - 4000:80

    labels:
      # 配置域名
       - "traefik.http.routers.cra.rule=Host(`gzb-full-stack.top`)"
      #  - "traefik.http.routers.cra.rule=Host(`8.134.97.101`)"

       # 配置 TLS
      #  - traefik.http.routers.cra.tls=true
      #  - traefik.http.routers.cra.tls.certresolver=le

  # traefik:
  #   image: traefik:v2.5
  #   command: --api.insecure=true --providers.docker
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

# 一定要与 traefik 在同一网络下
networks:
  default:
    external:
      name: traefik_default
