version: "3"
services:
  domain:
    build:
      context: .
      dockerfile: router.Dockerfile
    # ports:
    #   - 4000:80

    labels:
      # 配置域名
      #  - "traefik.http.routers.cra.rule=Host(`gzb-full-stack.top`)"
       - "traefik.http.routers.cra.rule=Host(`8.134.97.101`)"
       - "traefik.http.routers.dashboard.rule=Host(`8.134.97.101`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      #  - "traefik.http.routers.dashboard.service=api@internal"
      #  - "traefik.http.routers.dashboard.middlewares=auth"
      #  - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"

       # 配置 TLS
      #  - traefik.http.routers.cra.tls=true
      #  - traefik.http.routers.cra.tls.certresolver=le


# 一定要与 traefik 在同一网络下
networks:
  default:
    external:
      name: traefik_default
